### ISSUE TITLE
Почему никто кроме @asdminerpro не поставил проекту ★?

### ISSUE THREAD

**Issue by StephanYorchenko** [StephanYorchenko/such-a-lovely-js#19]
Разве вы не любите js?

**Comment by lololozhkin** [comment]
Я люблю. Просто забыл поставить.

**Comment by StephanYorchenko** [comment]
@lololozhkin моё почтение поклонникам js

**Comment by lololozhkin** [comment]
Прям чувствую что проект сделали как крутой проект. С доской, с ишью, с лицензией с контрибуторс.мд. поздравляю доузья! Хорошая работа!

**Comment by lololozhkin** [comment]
@StephanYorchenko Я приконнектил тг
